[envs_8266]
extends = common
platform = espressif8266
monitor_filters = ${common.monitor_filters}, esp8266_exception_decoder
build_flags = ${common.build_flags}

[envs_32]
extends = common
platform = espressif32
monitor_filters = ${common.monitor_filters}, esp32_exception_decoder
build_flags = ${common.build_flags}

[env:d1_mini_lite]
extends = envs_8266
board = d1_mini_lite
upload_port = COM6
monitor_port = COM6
build_flags = ${envs_8266.build_flags}
    -D PLATFORM=d1_mini_lite

[env:nodemcuv2]
extends = envs_8266
board = nodemcuv2
upload_port = COM6
monitor_port = COM6
build_flags = ${envs_8266.build_flags}
    -D PLATFORM=nodemcuv2

[env:d1_mini_32]
extends = envs_32
board = wemos_d1_mini32
; upload_port = COM5
; monitor_port = COM5
build_flags = ${envs_32.build_flags}
    -D PLATFORM=d1_mini_32

[env:devkit-32]
extends = envs_32
board = esp32doit-devkit-v1
build_flags = ${envs_32.build_flags}
    -D PLATFORM=devkit-32

[env:ota]
extends = envs_8266
board = d1_mini_lite
upload_protocol = espota
upload_port = 192.168.0.106
build_flags = ${envs_8266.build_flags}
    -D PLATFORM=d1_mini_lite

[env:ota-32]
extends = envs_32
board = wemos_d1_mini32
upload_protocol = espota
upload_port = 192.168.0.135
build_flags = ${envs_32.build_flags}
    -D PLATFORM=wemos_d1_mini32